version: '3.8'
services:
  case:
    image: deepf/deepcase:deepcase-19-menzorg
    networks:
      - network
    ports:
    - "3007:3007"
    depends_on:
    - "graphql-engine"
    restart: always
    pull_policy: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts: ['host.docker.internal:host-gateway']
networks:
  network:
    driver: bridge
